package com.wangchen.example.springboot.entity;

import java.util.Date;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.employee_id
     *
     * @mbggenerated
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.FIRST_NAME
     *
     * @mbggenerated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.LAST_NAME
     *
     * @mbggenerated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.PHONE_NUMBER
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.HIRE_DATE
     *
     * @mbggenerated
     */
    private Date hireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.JOB_ID
     *
     * @mbggenerated
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.SALARY
     *
     * @mbggenerated
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.commission_pct
     *
     * @mbggenerated
     */
    private Float commissionPct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.manager_id
     *
     * @mbggenerated
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.department_id
     *
     * @mbggenerated
     */
    private Integer departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.employee_id
     *
     * @return the value of employees.employee_id
     *
     * @mbggenerated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.employee_id
     *
     * @param employeeId the value for employees.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.FIRST_NAME
     *
     * @return the value of employees.FIRST_NAME
     *
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.FIRST_NAME
     *
     * @param firstName the value for employees.FIRST_NAME
     *
     * @mbggenerated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.LAST_NAME
     *
     * @return the value of employees.LAST_NAME
     *
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.LAST_NAME
     *
     * @param lastName the value for employees.LAST_NAME
     *
     * @mbggenerated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.EMAIL
     *
     * @return the value of employees.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.EMAIL
     *
     * @param email the value for employees.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.PHONE_NUMBER
     *
     * @return the value of employees.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.PHONE_NUMBER
     *
     * @param phoneNumber the value for employees.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.HIRE_DATE
     *
     * @return the value of employees.HIRE_DATE
     *
     * @mbggenerated
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.HIRE_DATE
     *
     * @param hireDate the value for employees.HIRE_DATE
     *
     * @mbggenerated
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.JOB_ID
     *
     * @return the value of employees.JOB_ID
     *
     * @mbggenerated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.JOB_ID
     *
     * @param jobId the value for employees.JOB_ID
     *
     * @mbggenerated
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.SALARY
     *
     * @return the value of employees.SALARY
     *
     * @mbggenerated
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.SALARY
     *
     * @param salary the value for employees.SALARY
     *
     * @mbggenerated
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.commission_pct
     *
     * @return the value of employees.commission_pct
     *
     * @mbggenerated
     */
    public Float getCommissionPct() {
        return commissionPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.commission_pct
     *
     * @param commissionPct the value for employees.commission_pct
     *
     * @mbggenerated
     */
    public void setCommissionPct(Float commissionPct) {
        this.commissionPct = commissionPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.manager_id
     *
     * @return the value of employees.manager_id
     *
     * @mbggenerated
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.manager_id
     *
     * @param managerId the value for employees.manager_id
     *
     * @mbggenerated
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.department_id
     *
     * @return the value of employees.department_id
     *
     * @mbggenerated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.department_id
     *
     * @param departmentId the value for employees.department_id
     *
     * @mbggenerated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
}