package com.wangchen.example.springboot.entity;

import java.util.Date;

public class GirlInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.age
     *
     * @mbggenerated
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.height
     *
     * @mbggenerated
     */
    private Byte height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.weight
     *
     * @mbggenerated
     */
    private Byte weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.chest
     *
     * @mbggenerated
     */
    private String chest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.waist
     *
     * @mbggenerated
     */
    private Byte waist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.hip
     *
     * @mbggenerated
     */
    private Byte hip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.shoe_size
     *
     * @mbggenerated
     */
    private Byte shoeSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.hair_style
     *
     * @mbggenerated
     */
    private String hairStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.hari_color
     *
     * @mbggenerated
     */
    private String hariColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.adress
     *
     * @mbggenerated
     */
    private String adress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.interest
     *
     * @mbggenerated
     */
    private String interest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.advatage
     *
     * @mbggenerated
     */
    private String advatage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.disadvatage
     *
     * @mbggenerated
     */
    private String disadvatage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.id
     *
     * @return the value of girl_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.id
     *
     * @param id the value for girl_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.name
     *
     * @return the value of girl_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.name
     *
     * @param name the value for girl_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.nickname
     *
     * @return the value of girl_info.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.nickname
     *
     * @param nickname the value for girl_info.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.age
     *
     * @return the value of girl_info.age
     *
     * @mbggenerated
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.age
     *
     * @param age the value for girl_info.age
     *
     * @mbggenerated
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.height
     *
     * @return the value of girl_info.height
     *
     * @mbggenerated
     */
    public Byte getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.height
     *
     * @param height the value for girl_info.height
     *
     * @mbggenerated
     */
    public void setHeight(Byte height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.weight
     *
     * @return the value of girl_info.weight
     *
     * @mbggenerated
     */
    public Byte getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.weight
     *
     * @param weight the value for girl_info.weight
     *
     * @mbggenerated
     */
    public void setWeight(Byte weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.chest
     *
     * @return the value of girl_info.chest
     *
     * @mbggenerated
     */
    public String getChest() {
        return chest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.chest
     *
     * @param chest the value for girl_info.chest
     *
     * @mbggenerated
     */
    public void setChest(String chest) {
        this.chest = chest == null ? null : chest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.waist
     *
     * @return the value of girl_info.waist
     *
     * @mbggenerated
     */
    public Byte getWaist() {
        return waist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.waist
     *
     * @param waist the value for girl_info.waist
     *
     * @mbggenerated
     */
    public void setWaist(Byte waist) {
        this.waist = waist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.hip
     *
     * @return the value of girl_info.hip
     *
     * @mbggenerated
     */
    public Byte getHip() {
        return hip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.hip
     *
     * @param hip the value for girl_info.hip
     *
     * @mbggenerated
     */
    public void setHip(Byte hip) {
        this.hip = hip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.shoe_size
     *
     * @return the value of girl_info.shoe_size
     *
     * @mbggenerated
     */
    public Byte getShoeSize() {
        return shoeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.shoe_size
     *
     * @param shoeSize the value for girl_info.shoe_size
     *
     * @mbggenerated
     */
    public void setShoeSize(Byte shoeSize) {
        this.shoeSize = shoeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.hair_style
     *
     * @return the value of girl_info.hair_style
     *
     * @mbggenerated
     */
    public String getHairStyle() {
        return hairStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.hair_style
     *
     * @param hairStyle the value for girl_info.hair_style
     *
     * @mbggenerated
     */
    public void setHairStyle(String hairStyle) {
        this.hairStyle = hairStyle == null ? null : hairStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.hari_color
     *
     * @return the value of girl_info.hari_color
     *
     * @mbggenerated
     */
    public String getHariColor() {
        return hariColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.hari_color
     *
     * @param hariColor the value for girl_info.hari_color
     *
     * @mbggenerated
     */
    public void setHariColor(String hariColor) {
        this.hariColor = hariColor == null ? null : hariColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.adress
     *
     * @return the value of girl_info.adress
     *
     * @mbggenerated
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.adress
     *
     * @param adress the value for girl_info.adress
     *
     * @mbggenerated
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.phone
     *
     * @return the value of girl_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.phone
     *
     * @param phone the value for girl_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.interest
     *
     * @return the value of girl_info.interest
     *
     * @mbggenerated
     */
    public String getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.interest
     *
     * @param interest the value for girl_info.interest
     *
     * @mbggenerated
     */
    public void setInterest(String interest) {
        this.interest = interest == null ? null : interest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.advatage
     *
     * @return the value of girl_info.advatage
     *
     * @mbggenerated
     */
    public String getAdvatage() {
        return advatage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.advatage
     *
     * @param advatage the value for girl_info.advatage
     *
     * @mbggenerated
     */
    public void setAdvatage(String advatage) {
        this.advatage = advatage == null ? null : advatage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.disadvatage
     *
     * @return the value of girl_info.disadvatage
     *
     * @mbggenerated
     */
    public String getDisadvatage() {
        return disadvatage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.disadvatage
     *
     * @param disadvatage the value for girl_info.disadvatage
     *
     * @mbggenerated
     */
    public void setDisadvatage(String disadvatage) {
        this.disadvatage = disadvatage == null ? null : disadvatage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.update_time
     *
     * @return the value of girl_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.update_time
     *
     * @param updateTime the value for girl_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl_info.create_time
     *
     * @return the value of girl_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl_info.create_time
     *
     * @param createTime the value for girl_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}