package com.wangchen.example.springboot.dao;

import com.wangchen.example.springboot.entity.GirlInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GirlInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl_info
     *
     * @mbggenerated
     */
    int insert(GirlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl_info
     *
     * @mbggenerated
     */
    int insertSelective(GirlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl_info
     *
     * @mbggenerated
     */
    GirlInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GirlInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GirlInfo record);
}